#!/bin/bash

# Pre-push hook to prevent pushes to master branch.

pushed_branch=`git rev-parse --abbrev-ref HEAD`

if [[ "$pushed_branch" == "master" ]]
then
  if [ -z "$FORCE" ]; then
    echo "A push to master was prevented - create a feature branch instead."
    echo "If you are *absolutely certain* what you are doing, re-run with FORCE=1."
    exit 1
  fi
fi
